learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
]

learning_logs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics', views.topics, name='topics'),
    path('topics/(?P<topic_id>\d+)', views.topic, name='topic'),
    path('new_topic', views.new_topic, name='new_topic'),
    path('new_entry/(?P<topic_id>\d+)', views.new_entry, name='new_entry'),
    path('edit_entry/(?P<entry_id>\d+)', views.edit_entry, name='edit_entry')
]





users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns=[
    path('login', LoginView.as_view(), {'template_name': 'users/registration/login.html'}, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):

    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        return self.text[:50] + "..."











users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Entry, Topic

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}


learning_logs/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from learning_logs.forms import EntryForm, TopicForm

from .models import Entry, Topic
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):

    return render(request, 'learning_logs/templates/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    # topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/templates/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries': entries}
    return render(request, 'learning_logs/templates/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
        
    context = {'form': form}
    return render(request, 'learning_logs/templates/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid:
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/templates/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'topic': topic, 'form': form, 'entry': entry}
    return render(request, 'learning_logs/templates/edit_entry.html', context)

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, logout, authenticate


# Create your views here.

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登陆，再重新定向到页面
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            print('test1123123123')
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/registration/register.html', context)       


learning_logs/templates/learning_logs/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http http-equiv="X-U-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a>Hello, {{user.username}}</a></li>
                <li><a href="{% url 'users:logout' %}">log out</a></li>
                {% else %}
                <li><a href="{% url 'users:register' %}">register</a></li>
                <li><a href="{% url 'users:login' %}">login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}
            {% endblock header %}
        </div>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>

</html>

learning_logs/templates/learning_logs/templates/edit_entry.html
{% extends "learning_logs/templates/base.html" %}


{% block content %}
<p>
    <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
</p>
<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/templates/index.html
{% extends "learning_logs/templates/base.html" %}

{% block header %}
<div class="jumbotron">
    <h1>Track your training.</h1>
</div>
{% endblock header %}

{% block content %}
<h2>
   <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log, and list the topics you're learning about. 
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry summarizing what you've learned.
</h2>

{% endblock content %}

learning_logs/templates/learning_logs/templates/new_entry.html
{% extends "learning_logs/templates/base.html" %}


{% block content %}
<a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit">add entry</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/templates/new_topic.html
{% extends "learning_logs/templates/base.html" %}

{% load bootstrap3 %}
{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
<button name="submit" class="btn btn-primary">add topic</button>
{% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/templates/topic.html
{% extends "learning_logs/templates/base.html" %}


{% block header %}
<h2>Topic: {{ topic }}</h2>
{% endblock header %}

{% block content %}

<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
    {% for entry in entries%}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ entry.date_added | date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                </small>
            </h3>
        </div>
        <div class="panel-body">{{entry.text | linebreaks}}</div>
    </div>
    <!-- <li>
            <p>{{ entry.date_added | date:'M d, Y H:i' }}</p>
            <p>{{ entry.text | linebreaks }}</p>
            <p>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
            </p>
        </li> -->
    {% empty%}
    There are no entries for this topic yet.
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/templates/topics.html
{% extends "learning_logs/templates/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}


{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
        </h3>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>

{% endblock content %}